### ISSUE TITLE
Null user page after submitting message feed

### ISSUE THREAD

**Issue by MCharming98** [maksymko/codeu-starter-project#28]
Step to reproduce: Run devserver on maven. After logging in, when clicking "submit" button on the user page to post a message, the user page is redirected to another user page which the username is null. This is not seen on the app engine on google cloud.

**Comment by MCharming98** [comment]
![Screen Shot 2019-03-08 at 11 33 56](https://user-images.githubusercontent.com/21093587/54076225-0fbe4e80-425e-11e9-9c40-feacbd239de1.png)

**Comment by maksymko** [comment]
Looks like this is the culprit: 4317f690a4bc147b45b38ea67eab2e33190e2ff8

Now, who can tell me what's wrong with it? PM me your answers and everyone who gets it right gets an Ice Cream :)

@tiananguyen this is your commit, so you get the honour of fixing it.
